### PR TITLE
1.17.x fabric

### PR DESCRIPTION
**Pull request by thatDudo**
#83 Port to 1.17

It was quite a bit of work.

I don't know how to merge into a new branch so you might have to change this pull request somehow?

Some things to mention:
- Iron Furnaces is not ported to 1.17 yet -> Commented out Integration
- The Integration into Origins is incomplete (not started)

Otherwise the obvious bugs are all fixed, heres a video:

https://user-images.githubusercontent.com/58403773/126638558-9a9c154f-88f1-43c5-9108-89717e1907ad.mp4

I have used the [medievalweapons mod](https://www.curseforge.com/minecraft/mc-mods/medievalweapons) in there.

Edit: I did not want to merge these 53 commits what the hell?

### CODE REVIEW

**Comment by TheIllusiveC4** [comment]
While I really appreciate the effort, the reason I haven't released an update to 1.17 yet is because I'm working on rewriting some key elements of Polymorph to streamline the mod and fix some core issues. Unfortunately, this means I likely won't be merging this as it would conflict with the work I've already done.

**Comment by TeoNikolov** [comment]
I apologize in advance since I have little experience working with pull requests on GitHub. What would be my options to get the pull request changes until the update to 1.17 is released? Do I need to clone thatDudo's repository and compile the jar myself?
Cheers!

**Comment by thatDudo** [comment]
I have just created an unofficial release here https://github.com/thatDudo/Polymorph/releases.
Of course you can also compile it yourself.

**Comment by TheIllusiveC4** [comment]
I've officially released 0.0.12-1.17.1 for Fabric, so I'm going to close this PR. Again, I appreciate the effort and it was helpful to use as reference while I was doing the porting from 1.16.5 to 1.17.1.

**Comment by thatDudo** [comment]
Well I'm glad I could help somehow. Congratulations for finishing the update.

**Pull request closed without merging**
